baseURL = "https://gg-scm.io/"
languageCode = "en-us"
title = "gg"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "Copyright © 2018–2024 The gg Authors"

[permalinks]
commands = "/cmd/:filename/"
workflows = "/workflow/:filename/"

[markup.highlight]
style = "github"

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "workflows"
name = "Workflows"
url = "/workflow/"
weight = 2

[[menu.main]]
identifier = "commands"
name = "Commands"
url = "/cmd/"
weight = 3

[[menu.main]]
identifier = "install"
name = "Install"
url = "/install/"
weight = 4

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/gg-scm/gg"
weight = 5

[params]
licenseURL = "https://github.com/gg-scm/gg-scm.io/blob/main/LICENSE"
latestRelease = "1.3.1"
releaseDate = "2023-12-01"
